### ISSUE TITLE
Weird crash [Smartphone] [Have crash log]

### ISSUE THREAD

**Issue by MrPurple666** [zloisupport/BaiduNetDiskTranslation#13]
**Describe the bug**
A strange crash after installation, the first time when opening it opens normally but then it just doesn't open and crash.
[Crash log from system](https://paste.crdroid.net/At9fJH) 

**To Reproduce**
1. Install
2. Open
3. After some time it crashes

**Expected behavior**
open normally 

**Screenshots**
[A video of the problem as a screenshot is not working in this case](https://youtube.com/shorts/A3ItMxgr_q8?feature=share) 

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9S
 - OS: CrDroid Android 12.1
 - Browser: Kiwi Browser (v103.0.5060.104)
 - Version: Baidu version (11.25.3 lite patch)

**Additional context**
I tested it on other versions of Android and the same error occurred.

**Comment by zloisupport** [comment]
Thanks for the report. Updated  the app to [ v11.27.4 ](https://rebrand.ly/bndAndroidMfire)

**Comment by MrPurple666** [comment]
Thanks! apparently fixed.
