### ISSUE TITLE
[Not an issue] How do you edit the compound file?

### ISSUE THREAD

**Issue by hgdagon** [zloisupport/BaiduNetDiskTranslation#3]
Hi, I found this repo just now. Thanks for the translations. I've been working on (Google) translating Baidu a long time ago, but I can't seem to remember how to edit the compound file in a way that Baidu would accept. I do remember there was a very specific method, but I forgot. Editing the zip is easy, just replace DuiStringTable.xml (or anything else), but I'm struggling with the compound file. Can you help?

**Comment by zloisupport** [comment]
Good afternoon, the current of the current noted your Comnetary. For files with files you need an SSView editor.

**Comment by hgdagon** [comment]
I assume you're referring to [the one by Mitec](https://www.mitec.cz/ssv.html), but I tried the trial version and it creates broken files (Baidu crashes/won't start). I also tried [OpenMCDF](https://github.com/ironfede/openmcdf) which I had used before, but it no longer works for the latest version, or I just forgot how to use it. I tried replacing StringTable.xml as well as recreating the whole coumpound file, but Baidu still won't start...

**Comment by zloisupport** [comment]
You can be a set of reasons so that the program does not work:
- broke some variable in stringtable.xml
- not the correct encoder in Structured Storage Viewer
