### ISSUE TITLE
Clicking Options button closes the program

### ISSUE THREAD

**Issue by MediaMaquina** [zloisupport/BaiduNetDiskTranslation#7]
When i click Settings and then Options. The program closes itself.
Latest version.

**Comment by zloisupport** [comment]
Specify the **version** and **language** of the installation.

**Comment by MediaMaquina** [comment]
I installed the latest version: BaiduNetdisk_7.7.7.1.exe
Using English(en-GB) v 7.7.2

**Comment by zloisupport** [comment]
Maybe I forgot to update. Try to download the mod installer. Or update the version and put release 7.7.8.1

**Comment by MediaMaquina** [comment]
Thanks that update fixed the problem.
